UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PROTEINA DE SOJA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01028');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BANANA DA PRATA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00006');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MORNING SHOT LATA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00631');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MANTEIGA',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00016');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PRESUNTO',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00018');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS QUEIJO MUSSARELA',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00019');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS REQUEIJAO CREMOSO',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00020');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ABACAXI',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00021');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS COUVE MANTEIGA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00025');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS LIMAO TAITI',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00029');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MANJERICAO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00030');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS OVO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00031');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS TOMATE',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00033');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS UVA ROXA SEM CAROCO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00034');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL DETERGENTE NEUTRO',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00037');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL SACO DE LIXO - 100 L',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00044');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� MORANGO CONGELADO 200 G',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00055');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� PREPARO A�AI CUPUACU',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00060');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PUDIM DE LICURI',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00667');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� PREPARO ACAI BANANA',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00058');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� PREPARO A�AI MORANGO',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00062');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP P� ABACAXI 180G',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00066');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP P� CACAU 100G',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00067');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP P� FRUTAS VERMELHAS',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00069');

UPDATE PRODUTOS SET 
    DESCRICAO = 'STROGONOFE CARNE',
    GRUPO = 'ALMO�O',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00811');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS LARANJA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00761');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS FILE DE FRANGO',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00073');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS QUEIJO MEIA CURA',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00762');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TAXA DE ENTREGA',
    GRUPO = 'DIVERSOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '99998');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TAXA DE SERVI�O',
    GRUPO = 'DIVERSOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '99999');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUPERCOFFEE PACOCA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00683');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUPERCOFFEE ORIGINAL',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00684');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACHE VANILA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00685');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACHE ORIGINAL',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00686');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACHE CHOCOLATE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00687');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BETTER PB LEITE EM PO',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00688');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BETTER PB COOKIES',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00689');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BETTER PB TRADICIONAL',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00690');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BETTER PB CHOCOLATE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00691');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACHE BPB TRADICIONAL',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00692');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SALADA CEASER',
    GRUPO = 'SALADAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00812');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL MOPI UMIDO',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00763');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MORNING SHOT SACHE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00632');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NAKED NUTS SACHE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00633');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD COOKIES AND CREAM',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00634');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD BROWNIE CRISPIES',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00635');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD BOMBOM CROCANTE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00636');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD LEITE AVELA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00637');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD THIN COOKIES AND CREAM',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00638');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD THIN CARAMELO AMENDOIM',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00639');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACHE CHOCONILA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00626');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD TUBE AVELA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00640');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD TUBE COOKIE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00641');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLD COOKIES BLACK',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00642');

UPDATE PRODUTOS SET 
    DESCRICAO = 'AGUA MINERAL S/ GAS',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00116');

UPDATE PRODUTOS SET 
    DESCRICAO = 'AGUA MINERAL C/ GAS',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00117');

UPDATE PRODUTOS SET 
    DESCRICAO = 'REFRIGERANTE COCA COLA',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00119');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACHE BPB COOKIES',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00693');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACHE BPB CHOCOLATE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00694');

UPDATE PRODUTOS SET 
    DESCRICAO = 'REFRIGERANTE COCA COLA ZERO',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00120');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PASTA MIX NUTS LEITE EM PO',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00643');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PASTA MIX NUTS SMORES',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00644');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PASTA CASTANHA CAJU COM CHOCOLATE BELGA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00645');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PASTA MIX NUTS AVELA BRANCO',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00646');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NAKED BITES AO LEITE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00647');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NAKED BITES BRANCO',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00648');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MIND DROPS',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00649');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUPERCOFFEE CHOCOLATE',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00650');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUPERCOFFEE VANILA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00651');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUPERCOFFEE CHOCONILA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00652');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CAPUCCINO',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00698');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MACHIATO',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00699');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS NIBS CACAU',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00772');

UPDATE PRODUTOS SET 
    DESCRICAO = 'VITAMINA MANA',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00704');

UPDATE PRODUTOS SET 
    DESCRICAO = 'AGUA DE COCO',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00705');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ICED VANILA LATE',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00708');

UPDATE PRODUTOS SET 
    DESCRICAO = 'LEITE VEGETAL',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00709');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PORTOBELO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00710');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS SHIMEJI',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00711');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ABACATE',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00712');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS WHEY',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00773');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CEBOLA BRANCA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00181');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PASTA DE AMENDOIM',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00774');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS GENGIBRE',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00775');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL ALCOOL 92,8',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00776');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CREME DE LEITE',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00777');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL ESPONJA DE ACO',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00778');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL ESPONJA DUPLA FACE',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00779');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL LUVA POLIETILENO',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00780');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS A�AI',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00781');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CALDA DE CHOCOLATE',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00782');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS EXTRATO BAUNILHA',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00783');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TOUCA DESCARTAVEL',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00203');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CHOCOLATE COM AVELA',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00784');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PASTA NAKED CHOCOLATE BELGA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00672');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL RODO PLASTICO',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00764');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MATCHA LATE',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00785');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CLICHE',
    GRUPO = 'ITENS NAO CONTROLAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00786');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EMB PAPEL MANTEIGA',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00787');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOBINA TERMICA',
    GRUPO = 'UTENS�LIOS SERVI�O',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00788');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MEL',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00789');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS POLVILHO AZEDO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00790');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS POLVILHO DOCE',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00791');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL VASSOURA',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00792');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL PAPEL TOALHA INTERFOLHADO',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00207');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL DESINFETANTE',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00208');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL ALCOOL LIQUIDO 70%',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00209');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL LUVA P/ LIMPEZA',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00210');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� BANANA PRATA 200G',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00216');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PES MESAS',
    GRUPO = 'ITENS NAO CONTROLAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00793');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BATATA BOLINHA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00714');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BROCOLIS NINJA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00715');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CROISSANT',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00794');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CENOURA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00716');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EMB PORTA TALHER',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00795');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MUSSARELA BUFALA',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00796');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PA�OCA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00797');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS COENTRO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00717');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS COUVE FLOR',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00718');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MAMAO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00719');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CAFE COADO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00798');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS LEITE EM PO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00799');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MORANGO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00720');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS AMORA CONGELADA',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00800');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS POLPA CACAU',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00801');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MORANGO CONGELADO',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00802');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PIMENTA DOCE',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00721');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS POLPA CUPUA�U',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00803');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS IOGURTE NATURAL',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00804');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS AZEITONA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00765');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS IOGURTE GREGO',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00805');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS AZEITE TRUFADO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00806');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PAO DE QUEIJO PRONTO KG',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00807');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS RUCULA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00722');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FILME PVC',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00766');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FILE FRANGO GRELHADO',
    GRUPO = 'ALMO�O',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00814');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SALADINHA VERDE COM PESTO',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00816');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS TOMATE CEREJA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00723');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS OLEO GIRASSOL',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00767');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS TESTES',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00808');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MANTEIGA SEM SAL',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00724');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS AGUA DE COCO NATURAL',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00809');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PALHA ITALIANA',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00810');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL PAPEL TOALHA ROLO',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00363');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS QUEIJO PARMESAO',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00725');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CROISSANT RECHEADO',
    GRUPO = 'CLASSICOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00817');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS AGUA DE COCO SO COCO',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00768');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS TOMATE PELATI',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00726');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUCO LARANJA COM MORANGO',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00747');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLO DO DIA',
    GRUPO = 'CLASSICOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00818');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CREAM CHEESE',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00727');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TOAST REQUEIJAO',
    GRUPO = 'TOASTS ESPECIAIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00819');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS SUCO DE LARANJA',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00728');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� SALADA VERDE COM PESTO',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00820');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� ARROZ 7 GR�OS',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00821');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� LEGUMES GRELHADOS',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00822');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� FETUCCINE MANTEIGA',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00823');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� FETUCCINE COM PESTO',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00824');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� DETOX',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00297');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� FETUCCINE COM MOLHO DE TOMATE',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00825');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS GRANOLA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00729');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOBINA 1',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00730');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS FLOCAO DE MILHO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00731');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS LEITE INTEGRAL',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00732');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL AGUA SANITARIA',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00733');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CEBOLA CONSERVA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00734');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUCO IMUNIDADE',
    GRUPO = 'SUCOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00815');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NOA MONTE SEU POKE PREMIUM',
    GRUPO = 'POKES NOA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01030');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� PURE DE BATATA',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00826');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PAPRICA DEFUMADA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00736');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOBINA PICOTADA 3',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00769');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PROT. NOA - OVO',
    GRUPO = 'NOA - PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '01031');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CHOCOLATE QUENTE',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00827');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CASTANHA QUEBRADA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00737');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MIRTILO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00738');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TORTA MOUSSE CHOCOLATE',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01032');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROT. NOA - SHIMEJI',
    GRUPO = 'NOA - EXTRA PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '01033');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MEL DE CACAU',
    GRUPO = 'SUCOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00828');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ALFACE LISA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00750');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS LIMAO SICILIANO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00751');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CAMARAO 4150',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00740');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS SALMAO FRESCO',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00741');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MARACUJA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00752');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PIMENTA CALABRESA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00753');

UPDATE PRODUTOS SET 
    DESCRICAO = 'AGUA TONICA',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00829');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PAO ITALIANO TRADICIONAL',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00742');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CAFE EM GRAOS',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00743');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MANGA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00755');

UPDATE PRODUTOS SET 
    DESCRICAO = 'JOGO AMERICANO',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00744');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL DESINCRUSTANTE',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00745');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP CAPUCCINO',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00746');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS OREGANO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00756');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BACON',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00757');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP SUCO LARANJA PROCESSADO',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00758');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SCHWEPPES CITRUS ZERO',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00830');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS AZEITE',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00759');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PAO DE FORMA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00760');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ACUCAR MASCAVO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00770');

UPDATE PRODUTOS SET 
    DESCRICAO = 'GAS',
    GRUPO = 'ITENS NAO CONTROLAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00771');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CHA DE LARANJA',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00831');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CHA CAPIM SANTO',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00832');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ALFACE AMERICANO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00326');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ALFACE CRESPA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00327');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ALFACE ROXA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00328');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MINI TORTINHA CAFE',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00833');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ABOBRINHA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00331');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ALHO',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00332');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MINI TORTINHA BANOFINHO',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00834');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MINI TORTINHA GOIABA',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00835');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PARMES�O',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00836');

UPDATE PRODUTOS SET 
    DESCRICAO = 'POTE CREATINA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00837');

UPDATE PRODUTOS SET 
    DESCRICAO = 'DOSE CREATINA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00838');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PASTA NAKED NUTS MACADAMIA',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00839');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BATATA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00841');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS KIWI',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00842');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL PANO MULTIUSO (PERFEX)',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00843');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SACO 10X15',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00844');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MA�� VERMELHA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00845');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ARROZ SETE GR�OS',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00846');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MOLHO SHOYU',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00847');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CANUDO PAPEL',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00848');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS LEITE CONDESADO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00850');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BATATA PALHA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00852');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS A�UCAR',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00851');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P�O LIBAN�S',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00849');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS FETTUCINNE',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00853');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ADO�ANTE SACH�',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00854');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS SAL REFINADO',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00855');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP A�AI BANANA',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00859');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP A�AI COM MORANGO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00861');

UPDATE PRODUTOS SET 
    DESCRICAO = 'LARIKINHA CAFE',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00864');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP A�AI COM CUPUA�U',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00862');

UPDATE PRODUTOS SET 
    DESCRICAO = 'LARIKINHA LICURI',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00865');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP SMOOTHIE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00863');

UPDATE PRODUTOS SET 
    DESCRICAO = 'LARIKINHA ORIGINAL',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00866');

UPDATE PRODUTOS SET 
    DESCRICAO = 'LARIKINHA NIBS',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00867');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL AROMATIZANTE BOM AR',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00868');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS SALSA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '00869');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CAF� FUNCION�RIOS',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00870');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL LUSTRA MOVEIS',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00871');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS SALM�O CONGELADO',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00873');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS A�UCAR CRISTAL SACH�',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00872');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MAIONESE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00875');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ETIQUETAS',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00877');

UPDATE PRODUTOS SET 
    DESCRICAO = 'HL SANITIZANTE HORTI FRUTI',
    GRUPO = 'MAT. LIMPEZA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00876');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ETIQUETA VALIDADE',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00878');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS VINAGRE DE MA��',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00879');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP CALDA FRUTAS VERMELHAS',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00880');

UPDATE PRODUTOS SET 
    DESCRICAO = 'KOMBUCHA ABACAXI COM HORTELA',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00484');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP CREME DE ABACATE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00881');

UPDATE PRODUTOS SET 
    DESCRICAO = 'KOMBUCHA MORANGO COM LIMAO',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00485');

UPDATE PRODUTOS SET 
    DESCRICAO = 'GUARDANAPO SACHE INDIVIDUAL',
    GRUPO = 'DESCARTAVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00479');

UPDATE PRODUTOS SET 
    DESCRICAO = 'KOMBUCHA PITAYA COM MARACUJA',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00486');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MOLHO CEASER',
    GRUPO = 'SALADAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00885');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PROTEINA BAUNILHA',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00887');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS TAPIOCA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00886');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUCO ABACAXI COM HORTELA',
    GRUPO = 'SUCOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00888');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SANDUBA OVO COM BACON',
    GRUPO = 'SANDUBAS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00889');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXPRESSO COM LEITE',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00890');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FLAT WHITE',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00891');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUMO DE LIM�O',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00892');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EMBALAGEM',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00893');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SANDUBA + FRANGO',
    GRUPO = 'SANDUBAS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00894');

UPDATE PRODUTOS SET 
    DESCRICAO = 'GRANOLA 250G',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00895');

UPDATE PRODUTOS SET 
    DESCRICAO = 'COMBO KIDS',
    GRUPO = 'COMBOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00896');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUCO LARANJA KIDS',
    GRUPO = 'SUCOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00897');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROTEINA BAUNILHA',
    GRUPO = 'A�A� / VITAMANA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00898');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TORTA DE CARAMELO',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00899');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BOLO DE BANANA ZERO',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00900');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CUSCUZ SIMPLES',
    GRUPO = 'CLASSICOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00901');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TORTA GOIABADA COM QUEIJO',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00902');

UPDATE PRODUTOS SET 
    DESCRICAO = 'POR��O FRUTAS COMBO',
    GRUPO = 'POR��ES EXTRA COZINHA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00907');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SANDUBA OVO COM BACON (C/ CAF�)',
    GRUPO = 'SANDUBAS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00908');

UPDATE PRODUTOS SET 
    DESCRICAO = 'TAXA ADICIONAL PLATAFORMA',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '99997');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SUPERCOFFEE 380G',
    GRUPO = 'EMPORIO',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00909');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CAF� DESCAFEINADO',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00910');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CAFE PEQUENO COM LEITE',
    GRUPO = 'CAF�S',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01040');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SALADA COM CAMAR�O',
    GRUPO = 'SALADAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00911');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIL� PARMEGIANA',
    GRUPO = 'ALMO�O',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00912');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BASE - SHARI',
    GRUPO = 'NOA - BASE',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00923');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BASE - MIX DE FOLHAS',
    GRUPO = 'NOA - BASE',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00924');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BASE - SHARI COM FURIKAKE',
    GRUPO = 'NOA - BASE',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00925');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA FRANGO',
    GRUPO = 'SALADAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00913');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PICADINHO FIL� MIGNON',
    GRUPO = 'ALMO�O',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00914');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CHEESECAKE PISTACHE',
    GRUPO = 'SOBREMESAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00915');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BASE - QUINOA',
    GRUPO = 'NOA - BASE',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00926');

UPDATE PRODUTOS SET 
    DESCRICAO = 'BASE - BIFUM',
    GRUPO = 'NOA - BASE',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00927');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PROT. NOA - SALMAO',
    GRUPO = 'NOA - PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00928');

UPDATE PRODUTOS SET 
    DESCRICAO = 'RED BULL 250ML',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00504');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - OVO COZIDO',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00936');

UPDATE PRODUTOS SET 
    DESCRICAO = 'RED BULL SUGAR FREE 250ML',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00505');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NOA MONTE SEU POKE',
    GRUPO = 'POKES NOA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00917');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NOA POKE CAMARAO',
    GRUPO = 'POKES NOA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00918');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CARNE DE FUMEIRO',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00513');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NOA POKE ATUM',
    GRUPO = 'POKES NOA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00919');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NOA POKE SALMAO',
    GRUPO = 'POKES NOA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00920');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NOA POKE 120G',
    GRUPO = 'POKES NOA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00921');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - CENOURA',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00937');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PROT. NOA - CAMARAO COZIDO',
    GRUPO = 'NOA - PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00929');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PROT. NOA - ATUM FRESCO',
    GRUPO = 'NOA - PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00930');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PROT. NOA - SHIMEJI',
    GRUPO = 'NOA - PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00931');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROT. NOA - ATUM FRESCO',
    GRUPO = 'NOA - EXTRA PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00932');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - MANGA',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00938');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - SUNOMONO DE PEPINO',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00939');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROT. NOA - SALMAO',
    GRUPO = 'NOA - EXTRA PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00933');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROT. NOA - CAMARAO',
    GRUPO = 'NOA - EXTRA PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00934');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROT. NOA - KANI COM CREAM CHEESE',
    GRUPO = 'NOA - EXTRA PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00935');

UPDATE PRODUTOS SET 
    DESCRICAO = 'NOA POKE VEGGIE',
    GRUPO = 'POKES NOA',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00922');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - TOMATE CEREJA ',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00940');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - BIFUM',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00941');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - EDAMAME',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00942');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - COUVE FRITA',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00943');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PROT. NOA - KANI COM CREAM CHEESE',
    GRUPO = 'NOA - PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '00969');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - CEBOLA ROXA',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00970');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CASTANHA DE CAJU CARAMELIZADA',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00971');

UPDATE PRODUTOS SET 
    DESCRICAO = 'P� CACAU COM MORANGO 200G',
    GRUPO = 'PORCIONADOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00560');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA - ABACATE',
    GRUPO = 'NOA - ACOMPANHAMENTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00951');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CHIPS DE BATATA DOCE',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00952');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - MAIONESE APIMENTADA ',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00953');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - WAKAME',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00954');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - GARI',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00955');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CHIPS COCO',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00956');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CRISPY CEBOLA',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00957');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - GERGELIM',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00958');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CEBOLINHA ',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00959');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - FLOR DE SAL',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00960');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CHIPS DE MANDIOQUINHA ',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00961');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - ALHO FRITO',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00962');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CASTANHA CAJU',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00963');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CERVEJA HEINEKEN',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00972');

UPDATE PRODUTOS SET 
    DESCRICAO = 'CERVEJA IPA',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '00973');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - WASABI',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00974');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - CREAM CHEESE',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00964');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - NORI ',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00965');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MOLHO NOA - TERIYAKI',
    GRUPO = 'NOA - MOLHOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00966');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MOLHO NOA - SHOYU',
    GRUPO = 'NOA - MOLHOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00967');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MOLHO NOA - CITRICO',
    GRUPO = 'NOA - MOLHOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00968');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS POLPA MANGA',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00987');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS IOGURTE ZERO LACTOSE',
    GRUPO = 'FRIOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00988');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS GOLDEN MILK',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00989');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS LEITE DE COCO EM PO',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00990');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS WHEY SHAKE',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00992');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP CUSCUZ BASE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00993');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BOLO BANANA PUR DOUX',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00994');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CHEESECAKE CARAMELO SALGADO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00995');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - MASSA HARUMAKI',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00975');

UPDATE PRODUTOS SET 
    DESCRICAO = 'FIN. NOA - TOMATE SECO',
    GRUPO = 'NOA - FINALIZACOES',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00976');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CHEESECAKE GOIABADA',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00996');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS GOMA TAPIOCA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00997');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP RECHEIO DE FRANGO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00998');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP ALHO BATIDO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00999');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP MOLHO TOMATE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01000');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP RECHEIO FUMEIRO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01001');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROT. NOA - FRANGO GRELHADO',
    GRUPO = 'NOA - EXTRA PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '01037');

UPDATE PRODUTOS SET 
    DESCRICAO = 'EXTRA PROT. NOA - CAMAR�O EMPANADO',
    GRUPO = 'NOA - EXTRA PROTEINA',
    COD_PLANO_CONTAS = '209007'
WHERE (COD_PRODUTO = '01038');

UPDATE PRODUTOS SET 
    DESCRICAO = 'MOLHO NOA - SPICY MAYO',
    GRUPO = 'NOA - MOLHOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01039');

UPDATE PRODUTOS SET 
    DESCRICAO = 'KIRO',
    GRUPO = 'OUTRAS BEBIDAS',
    COD_PLANO_CONTAS = '211001'
WHERE (COD_PRODUTO = '01041');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS SAL SACHE',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01042');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MOLHO DEMIGLACE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01043');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP MOLHO PESTO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01002');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP RECHEIO COGUMELO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01003');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP TORTA PISTACHE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01004');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP TORTINHA GOIABA',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01005');

UPDATE PRODUTOS SET 
    DESCRICAO = 'PORCAO PAO DE QUEIJO',
    GRUPO = 'CLASSICOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00624');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP TORTINHA BANOFE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01006');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP TORTINHA CAFE',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01007');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP CREME AZEDO',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01008');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP MORANGO CONGELADO 75G',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01009');

UPDATE PRODUTOS SET 
    DESCRICAO = 'SBP AMORA CONGELADA 75G',
    GRUPO = 'SUBPRODUTOS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01010');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS HORTEL�',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '01011');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA - OVO COZIDO',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00978');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA - CEBOLA ROXA',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00979');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA - CENOURA',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00980');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA MANGA',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00981');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA - SUNOMONO DE PEPINO',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00982');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA - TOMATE CEREJA',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00983');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA - BIFUM',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00984');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA - COUVE FRITA',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00985');

UPDATE PRODUTOS SET 
    DESCRICAO = 'ACOMP. NOA EXTRA  ABACATE',
    GRUPO = 'NOA - ACOMPANHAMENTOS EXTRAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '00986');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MANDIOQUINHA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '01013');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ATUM HIDROGENADO',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01014');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ARROZ JAPONES',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01015');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS EDAMAME',
    GRUPO = 'CONGELADOS ',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01016');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS KANI',
    GRUPO = 'PROTE�NAS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01017');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BIFUM',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01018');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CEBOLA ROXA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '01019');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ACELGA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '01020');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS BANANA DA TERRA',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '01021');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS CANELA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01022');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS MA�A VERDE',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '01023');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS PEPINO JAPONES',
    GRUPO = 'HORTIFRUTI',
    COD_PLANO_CONTAS = '209001'
WHERE (COD_PRODUTO = '01024');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS AZEITE EXTRA VIRGEM CLIENTE',
    GRUPO = 'INSUMOS BAR',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01025');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS ALCAPARRA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01026');

UPDATE PRODUTOS SET 
    DESCRICAO = 'INS FARINHA DE MANDIOCA',
    GRUPO = 'NAO PERECIVEIS',
    COD_PLANO_CONTAS = '000000'
WHERE (COD_PRODUTO = '01027');



COMMIT WORK;

